# Generated by Django 4.2.7 on 2023-11-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upload_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
